### ISSUE TITLE
Error installing Jekyll - Ubuntu

### ISSUE THREAD

**Issue by james-wright19** [jekyll/jekyll-help#120]
When I try to install Jekyll I get this error:

```
 sudo gem install jekyll
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
    ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/fast-stemmer-1.0.2 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/fast-stemmer-1.0.2/ext/gem_make.out
```

And here is a copy of the file that it links to:

```
/usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:1:in `<main>'
```

Thanks in advance!

**Comment by thawn** [comment]
I had the same error and can confirm that the suggestion from penibelst helped.
However, I did run apt-get build-dep jekyll before. Should this not have taken care of installing ruby1.9.1-dev?

**Comment by alexandre-mbm** [comment]
``` sh
$ sudo apt-get install ruby-dev
```

Ref.: http://stackoverflow.com/a/8113213
