### ISSUE TITLE
SASS won’t compile with jekyll build

### ISSUE THREAD

**Issue by ndarville** [jekyll/jekyll-help#132]
On [this](https://github.com/ndarville/jekyll-boilerplate/blob/699840d35521e01c79a4c2d4a9e13887ede120f2/static/css/style.scss) project (YAML header included in local version), I get the error below, when running `jekyll build --trace`.

I have tried appending `.scss` to the imports, but I get the same error.

```sh
$ jekyll build --trace
Notice: for 10x faster LSI support, please install http://rb-gsl.rubyforge.org/
Configuration file: none
            Source: /jekyll-boilerplate/static/css
       Destination: /jekyll-boilerplate/static/css/_site
      Generating... 
  Conversion error: There was an error converting 'style.scss'.
(sass):1: File to import not found or unreadable: _reset. (Sass::SyntaxError)
```

```sh
Load path: /jekyll-boilerplate/static/css/_sass
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/import_node.rb:66:in `rescue in import'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/import_node.rb:45:in `import'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/import_node.rb:28:in `imported_file'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/import_node.rb:37:in `css_import?'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/perform.rb:283:in `visit_import'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/base.rb:36:in `visit'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/perform.rb:152:in `block in visit'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/stack.rb:79:in `block in with_base'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/stack.rb:121:in `with_frame'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/stack.rb:79:in `with_base'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/perform.rb:152:in `visit'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/base.rb:52:in `map'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/base.rb:52:in `visit_children'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/perform.rb:161:in `block in visit_children'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/perform.rb:173:in `with_environment'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/perform.rb:160:in `visit_children'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/base.rb:36:in `block in visit'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/perform.rb:180:in `visit_root'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/base.rb:36:in `visit'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/perform.rb:151:in `visit'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/visitors/perform.rb:8:in `visit'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/root_node.rb:36:in `css_tree'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/tree/root_node.rb:20:in `render'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass/engine.rb:274:in `render'
    from /.rvm/gems/ruby-2.1.0/gems/sass-3.3.14/lib/sass.rb:62:in `compile'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-sass-converter-1.2.0/lib/jekyll/converters/scss.rb:93:in `convert'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/convertible.rb:65:in `transform'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/convertible.rb:212:in `do_layout'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/page.rb:122:in `render'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/site.rb:261:in `block in render'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/site.rb:260:in `each'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/site.rb:260:in `render'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/site.rb:43:in `process'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/command.rb:53:in `process_site'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/commands/build.rb:50:in `build'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/commands/build.rb:33:in `process'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/lib/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
    from /.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `call'
    from /.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `block in execute'
    from /.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `each'
    from /.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `execute'
    from /.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.4/lib/mercenary/program.rb:35:in `go'
    from /.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.4/lib/mercenary.rb:22:in `program'
    from /.rvm/gems/ruby-2.1.0/gems/jekyll-2.2.0/bin/jekyll:18:in `<top (required)>'
    from /.rvm/gems/ruby-2.1.0/bin/jekyll:23:in `load'
    from /.rvm/gems/ruby-2.1.0/bin/jekyll:23:in `<main>'
    from /.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
    from /.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

The relevant part of `_config.yml`:

```yaml
sass:
    sass_dir: static/css/
    style: :nested
```

**Comment by guy-mograbi-at-gigaspaces** [comment]
I am still experiencing issues. 
I have the structure, I have the header, I have the partials - all working with "jekyll serve". 
The style appears on page and everything is good. 

but when I do "jekyll build" I get something totally wrong. 

my structure is what I got after following: http://markdotto.com/2014/09/25/sass-and-jekyll/

+root
     +---- _sass 
                  +---- _myPartial.scss
     + ---- css 
                  +---- main.scss

but I do "jekyll build" I get 
_site/css/main.scss

the file does not seem to be compiled. 

the partial is not found under the `_site` directory.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
