### ISSUE TITLE
when running jekyll serve ,error occurred,hitimes/hitimes (LoadError)

### ISSUE THREAD

**Issue by supercafe2013** [jekyll/jekyll-help#192]
Hi ,
I'm the greener to jekyll,after I installed Jekyll and run for it,error happened...
According to the clues, I installed hittimes,but the problems still exists.
```
/Users/supercafe/my-awsome-site
supercafes-MacBook-Pro:my-awsome-site supercafe$ jekyll serve
Configuration file: /Users/supercafe/my-awsome-site/_config.yml
            Source: /Users/supercafe/my-awsome-site
       Destination: /Users/supercafe/my-awsome-site/_site
      Generating...
                    done.
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- hitimes/hitimes (LoadError)
	from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/hitimes-1.2.2/lib/hitimes.rb:37:in `rescue in <top (required)>'
	from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/hitimes-1.2.2/lib/hitimes.rb:32:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/timers-4.0.1/lib/timers/group.rb:4:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/timers-4.0.1/lib/timers.rb:4:in `<top (required)>'

```

**Comment by AlejandroCruz** [comment]
I read that you were successful in resolving this issue in https://github.com/jekyll/jekyll/issues/3092 , how did you do it. Did you uninstall and reinstall hitimes and timers specifying versions? I tried the uninstall of both gems and then installing them and it did not resolve my issue. I was wondering if I missed a step or something.

**Comment by albertogg** [comment]
It seems like, I'll close the issue! thanks.
