### ISSUE TITLE
Jekyll::Watcher Error

### ISSUE THREAD

**Issue by seniorokur** [jekyll/jekyll-help#294]
Hello,

Jekyll used to work on my computer before but when i tried to install octopress suddenly it became broken. 

The error output is : 
```
seniorokur@dell-Inspiron-5521:~/Masaüstü/site/sa$ jekyll build --watch
Configuration file: /home/seniorokur/Masaüstü/site/sa/_config.yml
            Source: /home/seniorokur/Masaüstü/site/sa
       Destination: /home/seniorokur/Masaüstü/site/sa/_site
      Generating... 
                    done.
jekyll 2.5.3 | Error:  uninitialized constant Jekyll::Watcher
```

What should i do?

**Comment by lkwg82** [comment]
I had the same issue. I mixed system packages and manual `gem` versions and did following steps to solve the problem:
-  purge ruby installation
- reinstall ruby and ruby-dev (ubuntu)
- `gem install jekyll jekyll-watch`

now it runs!

**Comment by talhaokur** [comment]
I did

```
sudo apt-get purge ruby
sudo apt-get install ruby-full
sudo gem install jekyll jekyll-watch
sudo gem install execjs
```

But now I have different problem. What's wrong? Here is the output:

```
seniorokur@dell-Inspiron-5521:~/Masaüstü$ jekyll create new
/var/lib/gems/2.1.0/gems/execjs-2.5.2/lib/execjs/runtimes.rb:48:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
    from /var/lib/gems/2.1.0/gems/execjs-2.5.2/lib/execjs.rb:5:in `<module:ExecJS>'
    from /var/lib/gems/2.1.0/gems/execjs-2.5.2/lib/execjs.rb:4:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /var/lib/gems/2.1.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /var/lib/gems/2.1.0/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /var/lib/gems/2.1.0/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:46:in `block in gracefully_require'
    from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `each'
    from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `gracefully_require'
    from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll.rb:166:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by kleinfreund** [comment]
It complains about a missing Javascript runtime like nodejs. Not exactly sure whether this is a necessity in all cases.

**Comment by talhaokur** [comment]
For now it works without a problem after i re-install node js. Thanks!

**Comment by gabrsar** [comment]
I'm with this same problem. Tried everything. Only @lkwg82 and @seniorokur aswers save me. There are exactly steps that I'de done:

```
apt-get purge jekyll
apt-get purge ruby
apt-get purge nodejs
apt-get purge npm
apt-get autoclean
apt-get update
apt-get install ruby
apt-get install nodejs
apt-get install npm
apt-get install ruby-dev
gem install jekyll jekyll-watch
```

And them. Works :)

Thank you.

**Comment by ehernandez-xk** [comment]
Hi everyone
I reviewed everywhere and I didn't find how to fix my jekyll installation, I already tested on Mac my jekyll project and works perfect.

I tired all you post and it still the same error. any idea?
jekyll 3.1.2 | Error:  uninitialized constant Jekyll::Watcher

My laptop has:
Deban 8 (jessie 64 bits)
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
jekyll 3.1.2

**Comment by parkr** [comment]
@ehernandez-xk Run `gem uninstall jekyll` and `gem uninstall jekyll-watcher` then run `gem install jekyll` again. Somewhere it's using the wrong version of `jekyll-watch`.

**Comment by ehernandez-xk** [comment]
@parkr Hi, the problem is still there.

jekyll 3.1.2 | Error:  uninitialized constant Jekyll::Watcher

**Comment by mjpost** [comment]
I have this problem, too. Mac OS X 10.11.3, ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]. I tried removing jekyll and jekyll-watch and then reinstalling them, to no avail:

```
$ jekyll build --destination ../site
Configuration file: /Users/post/Sites/repo/_config.yml
            Source: /Users/post/Sites/repo
       Destination: ../site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Deprecation: posts.each should be changed to posts.docs.each.
                    Called by /Library/Ruby/Gems/2.0.0/gems/jekyll-redirect-from-0.8.0/lib/jekyll-redirect-from/redirector.rb:13:in `generate_alt_urls'.
jekyll 3.1.2 | Error:  uninitialized constant Jekyll::Post
```

UPDATE: this was resolved by updating jekyll-redirect-from, as I should have seen before posting.

**Comment by narthur** [comment]
I had the same issue and this line fixed it for me:

```
sudo apt-get purge ruby-jekyll-watch
```
