### ISSUE TITLE
Liquid Exception: cannot load such file -- yajl/2.0/yajl

### ISSUE THREAD

**Issue by rdquintas** [jekyll/jekyll-help#50]
Hi,
When I run jekyll build command on windows I get this error.
:o(

``` text
C:\Users\rdquintas\Desktop\jek\zrq>jekyll build
Configuration file: C:/Users/rdquintas/Desktop/jek/zrq/_config.yml
            Source: C:/Users/rdquintas/Desktop/jek/zrq
       Destination: C:/Users/rdquintas/Desktop/jek/zrq/_site
      Generating...
  Liquid Exception: cannot load such file -- yajl/2.0/yajl in _posts/2014-05-21-
welcome-to-jekyll.markdown
C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': c
annot load such file -- yajl/2.0/yajl (LoadError)
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/yajl-ruby-1.1.0-x86-mingw32/lib
/yajl/yajl.rb:2:in `<top (required)>'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/yajl-ruby-1.1.0-x86-mingw32/lib
/yajl.rb:1:in `<top (required)>'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:i
n `require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:i
n `rescue in require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:i
n `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/pygments.rb-0.5.4/lib/pygments/
popen.rb:3:in `<top (required)>'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/pygments.rb-0.5.4/lib/pygments.
rb:1:in `<top (required)>'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/tags/hi
ghlight.rb:53:in `render_pygments'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/tags/hi
ghlight.rb:41:in `render'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/block.r
b:106:in `block in render_all'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/block.r
b:93:in `each'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/block.r
b:93:in `render_all'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/block.r
b:82:in `render'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/templat
e.rb:124:in `render'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/liquid-2.5.5/lib/liquid/templat
e.rb:132:in `render!'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/convert
ible.rb:96:in `render_liquid'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/convert
ible.rb:170:in `do_layout'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/post.rb
:266:in `render'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/site.rb
:245:in `block in render'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/site.rb
:244:in `each'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/site.rb
:244:in `render'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/site.rb
:43:in `process'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/command
.rb:43:in `process_site'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/command
s/build.rb:46:in `build'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/command
s/build.rb:30:in `process'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/lib/jekyll/command
s/build.rb:17:in `block (2 levels) in init_with_program'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/c
ommand.rb:220:in `call'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/c
ommand.rb:220:in `block in execute'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/c
ommand.rb:220:in `each'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/c
ommand.rb:220:in `execute'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary/p
rogram.rb:35:in `go'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.3/lib/mercenary.r
b:22:in `program'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.0.3/bin/jekyll:18:in `
<top (required)>'
        from C:/Ruby200/bin/jekyll:23:in `load'
        from C:/Ruby200/bin/jekyll:23:in `<main>'

C:\Users\rdquintas\Desktop\jek\zrq>
```

**Comment by XhmikosR** [comment]
This is definitely an issue and I'm still trying to find a sensible fix.

https://ci.appveyor.com/project/XhmikosR/pages-gem/build/28/job/j75kggkac3fh2l2k

**Comment by morenoh149** [comment]
I'm getting this now as well. `gem install rouge` did not fix it. Perhaps this is due to the 2 -> 3 update?
`gem update jekyll` didn't fix this for me. My Gemfile

```
GEM
  remote: https://rubygems.org/
  specs:
    blankslate (2.1.2.4)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    classifier-reborn (2.0.3)
      fast-stemmer (~> 1.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorator (0.1)
    execjs (2.5.2)
    fast-stemmer (1.0.2)
    ffi (1.9.10)
    hitimes (1.2.2)
    jekyll (2.5.3)
      classifier-reborn (~> 2.0)
      colorator (~> 0.1)
      jekyll-coffeescript (~> 1.0)
      jekyll-gist (~> 1.0)
      jekyll-paginate (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 2.6.1)
      mercenary (~> 0.3.3)
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      safe_yaml (~> 1.0)
      toml (~> 0.1.0)
    jekyll-coffeescript (1.0.1)
      coffee-script (~> 2.2)
    jekyll-gist (1.2.1)
    jekyll-paginate (1.1.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-sitemap (0.7.0)
    jekyll-watch (1.2.1)
      listen (~> 2.7)
    kramdown (1.8.0)
    liquid (2.6.2)
    listen (2.10.1)
      celluloid (~> 0.16.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    mercenary (0.3.5)
    parslet (1.5.0)
      blankslate (~> 2.0)
    posix-spawn (0.3.11)
    pygments.rb (0.6.3)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rb-fsevent (0.9.5)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    redcarpet (3.3.2)
    safe_yaml (1.0.4)
    sass (3.4.16)
    timers (4.0.1)
      hitimes
    toml (0.1.2)
      parslet (~> 1.5.0)
    yajl-ruby (1.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll
  jekyll-sitemap

BUNDLED WITH
   1.10.4
```

**Comment by morenoh149** [comment]
removing `highligher: rouge` from my _config.yml file worked for me
